[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cuda-intro-docs"
authors = [{name = "seanwang", email = "seanwang@mail.com"}]
dynamic = ["version", "description"]
